### ISSUE TITLE
NuGet packages

### ISSUE THREAD

**Issue by cn12023** [OS2CPRbroker/CPRbroker#17]
What NuGet packages is required for the solution to build correctly? 
Is there a list of packages available?

I can see that log4net is used, but version 2.0.12 is not enough

**Comment by heiniovason** [comment]
_What NuGet packages is required for the solution to build correctly?_

If a package is missing when you build the 3 separat projects then it will list what packages are are missing. The packages are declared in package.config and/or PackageReference(in project file) in main or sub projects.
You can see packages installed in: Tools -> NuGet Package Manager -> Manage NuGet Packages for Solution ...

Build order:

_It's a good idea to Clean all three projects before proceeding._

1. Core
2. CprBroker
3. EventBroker
4. CprBroker

_"I can see that log4net is used, but version 2.0.12 is not enough"_

Missing and/or non-updated assembly refernces are now included if you pull current(commit a5a5ea8) development branch.
